# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: hazardlib + engine tests

on:
  pull_request:

jobs:
  engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install pytest
        pip install fiona pyshp
        pip install -r requirements-py39-linux64.txt && pip install -e .
        python -c'import shapely as s; print("shapely=%s" % s.__version__)'
    - name: Test with pytest
      run: |
        oq dbserver start
        pytest --doctest-modules -x --disable-warnings --color=yes --durations=10 openquake/calculators && pytest doc/adv-manual/*.rst

  hazardlib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install fiona pyshp
        pip install pytest
        pip install -r requirements-py38-linux64.txt && pip install -e .
    - name: hazardlib tests
      run: |
        oq dbserver start
        cd openquake && pytest -x --doctest-modules --disable-warnings --color=yes --durations=10 hazardlib commands engine hmtk risklib server commonlib baselib
